# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='legajo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
